In [3]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
df = pd.read_csv("./SteelPlateFaults-2class.csv")
df.head()

X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0       1325       1339      30207      30238           268           29   
1          1         16      55572      55629           370           48   
2       1323       1333      68445      68506           330           48   
3       1324       1333      75642      75681           207           25   
4       1324       1335      97132      97213           594           55   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
0           31              25809                     79   
1           62              39293                     27   
2           61              33449                     90   
3           39              21354                     93   
4           81              61608                     93   

   Maximum_of_Luminosity  ...  Edges_X_Index  Edges_Y_Index  \
0                    124  ...         0.4828         1.0000   
1                    119  ...         0.3125         0.9194   
2                    119  ...         0.2083         1.0000   
3                    124  ...         0.3600         1.0000   
4                    125  ...         0.2000         1.0000   

   Outside_Global_Index  LogOfAreas  Log_X_Index  Log_Y_Index  \
0                   1.0      2.4281       1.1461       1.4914   
1                   1.0      2.5682       1.1761       1.7559   
2                   1.0      2.5185       1.0000       1.7853   
3                   1.0      2.3160       0.9542       1.5911   
4                   1.0      2.7738       1.0414       1.9085   

   Orientation_Index  Luminosity_Index  SigmoidOfAreas  Class  
0             0.5484           -0.2476          0.7065      1  
1             0.7368           -0.1703          0.9755      1  
2             0.8361           -0.2081          0.8861      1  
3             0.7692           -0.1941          0.5805      1  
4             0.8642           -0.1897          0.9806      1  

[5 rows x 28 columns]

In [5]:
df.describe()

X_Minimum    X_Maximum     Y_Minimum     Y_Maximum   Pixels_Areas  \
count  1119.000000  1119.000000  1.119000e+03  1.119000e+03    1119.000000   
mean    505.691689   575.336908  1.559346e+06  1.559417e+06    3032.825737   
std     516.588405   482.705270  1.736716e+06  1.736739e+06    6536.594600   
min       0.000000     4.000000  6.712000e+03  6.724000e+03       2.000000   
25%      41.000000   194.000000  3.786385e+05  3.786720e+05     104.000000   
50%     270.000000   340.000000  1.094338e+06  1.094348e+06     276.000000   
75%     967.000000   990.500000  2.143707e+06  2.143718e+06    5292.000000   
max    1705.000000  1713.000000  1.241645e+07  1.241647e+07  152655.000000   

        X_Perimeter   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  \
count   1119.000000   1119.000000       1.119000e+03            1119.000000   
mean     168.374441    118.453083       3.309396e+05              81.152815   
std      383.483310    556.835707       6.412347e+05              37.709924   
min        2.000000      1.000000       2.500000e+02               0.000000   
25%       18.000000     16.000000       1.226950e+04              43.000000   
50%       42.000000     37.000000       3.036100e+04              87.000000   
75%      229.500000    132.000000       5.251185e+05             109.000000   
max    10449.000000  18152.000000       1.159141e+07             203.000000   

       Maximum_of_Luminosity  ...  Edges_X_Index  Edges_Y_Index  \
count            1119.000000  ...    1119.000000    1119.000000   
mean              132.609473  ...       0.592365       0.732219   
std                21.004224  ...       0.253715       0.254367   
min                37.000000  ...       0.014400       0.048400   
25%               124.000000  ...       0.360900       0.491850   
50%               129.000000  ...       0.621300       0.794900   
75%               141.000000  ...       0.788900       1.000000   
max               253.000000  ...       1.000000       1.000000   

       Outside_Global_Index   LogOfAreas  Log_X_Index  Log_Y_Index  \
count           1119.000000  1119.000000  1119.000000  1119.000000   
mean               0.511618     2.745436     1.505165     1.503027   
std                0.492201     0.858010     0.539412     0.477951   
min                0.000000     0.301000     0.301000     0.000000   
25%                0.000000     2.017000     1.041400     1.146100   
50%                0.500000     2.440900     1.322200     1.462400   
75%                1.000000     3.723650     2.156850     1.832500   
max                1.000000     5.183700     3.074100     4.258700   

       Orientation_Index  Luminosity_Index  SigmoidOfAreas        Class  
count        1119.000000       1119.000000     1119.000000  1119.000000  
mean           -0.007623         -0.114350        0.672209     0.650581  
std             0.533879          0.166025        0.340823     0.477000  
min            -0.991000         -0.998900        0.119000     0.000000  
25%            -0.567650         -0.190000        0.299800     0.000000  
50%             0.000000         -0.121100        0.815300     1.000000  
75%             0.457400         -0.058000        1.000000     1.000000  
max             0.991700          0.642100        1.000000     1.000000  

[8 rows x 28 columns]

In [6]:
print("Number of Tuples: " + str(len(df)))

Number of Tuples: 1119


In [7]:
# l = (int)(0.7*len(df))
# # train_data = df.iloc[:l]
# # test_data = df.iloc[l:]
# # print(l,len(train_data),len(test_data))

In [8]:
# train_data.head()
# test_data.head()

In [9]:
y = df['Class']
X = df.drop('Class', axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42,shuffle = True)
k_values = [1,3,5]

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors = k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    cm= confusion_matrix(y_test, y_pred)
    print ("Accuracy for k = " + str(k) + ": ", accuracy_score(y_test, y_pred))
    print(cm)

Accuracy for k = 1:  0.8392857142857143
[[ 81  27]
 [ 27 201]]
Accuracy for k = 3:  0.8898809523809523
[[ 83  25]
 [ 12 216]]
Accuracy for k = 5:  0.8958333333333334
[[ 82  26]
 [  9 219]]


In [10]:
min_max = MinMaxScaler()
N=min_max.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(N, y, test_size = 0.3, random_state = 42,shuffle = True)
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors = k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    cm= confusion_matrix(y_test, y_pred)
    print ("Accuracy for k = " + str(k) + ": ", accuracy_score(y_test, y_pred))
    print(cm)


Accuracy for k = 1:  0.9613095238095238
[[104   4]
 [  9 219]]
Accuracy for k = 3:  0.9702380952380952
[[104   4]
 [  6 222]]
Accuracy for k = 5:  0.9642857142857143
[[103   5]
 [  7 221]]
